server:
  port: 8081
spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    generate-ddl: false
    show-sql: true
  datasource:
    url: "jdbc:postgresql://rc1a-uiaek510ekpcnict.mdb.yandexcloud.net:6432/forkjoinbd"
    username: "postgresql"
    password: "postgresql"
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db.changelog/db.changelog-master.yaml
  cache:
    type: redis
  data:
    redis:
      port: 6379
      host: "c-c9qfajrlp2bb7l2u11h3.rw.mdb.yandexcloud.net"
      password: "redis891"
